services:
  fhir-sparql-js:
    container_name: fhir-sparql-js
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - fhir-network

networks:
  fhir-network:
    name: fhir-network
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.113.0.0/16
