name: 'jest-coverage'
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build
              run: npm run build
            - uses: ArtiomTr/jest-coverage-report-action@v2
